# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18aOE_n_TqgGxUEhaC6Jrhb2s9Bpyjuax
"""

def tashxis(belgi):
  from IPython.display import Image
  if belgi == "Istma":
    print("Davolash usuli: Parasitamol iching ")
    display(Image(filename='parat.jpg'))
    return "Parasitamol iching"
  elif belgi == "Bosh og'rig'i":
    print("Davolash usuli: Bol nol iching ")
    display(Image(filename='bolnol.jpg'))
    return "Bol nol iching"
  elif belgi == "Grip":
    print("Davolash usuli: Tylol Hot iching ")
    display(Image(filename='Tylolhot.png'))
    return "Tylol Hot iching"
  elif belgi == "Saraton":
    print("Davolash usuli: Davosi yo'q oilangiz bilan hayrlashing ")
    display(Image(filename='ajal.jpg'))
    return "Davosi yo'q oilangiz bilan hayrlashing"
  elif belgi == "Tish og'rig'i":
    print("Davolash usuli: Quepen iching")
    display(Image(filename='kyupen.png'))
    return "Quepen iching"
  elif belgi == "Husnbuzar":
    print("Davolash usuli: KuriOzin gel surting")
    display(Image(filename='kuriozin gel.jpg'))
    return "KuriOzin gel surting"
  else:
    print("Davolash usuli: Shifokorga murojat qiling ")
    display(Image(filename='shifokor.jpg'))
    return "Shifokorga murojat qiling"
belgi = input("Kasllik belgisini kiriting   ")
natija= tashxis(belgi)
print(natija)